plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-feed

title: Code, the Universe and Everything
description: A blog about code, the universe and everything.
author: Sören Köhler

feed:
  posts_limit: 50